#!/bin/bash
# RestoreFixer 1.0 (4/23/2024) by Gordon Emmerson at Retrospekt

DevAgent="AMPDevicesAgent"

DiscoAgent="AMPDeviceDiscoveryAgent"

DiscoAgentPath="/System/Library/PrivateFrameworks/AMPDevices.framework/Versions/A/Support/AMPDeviceDiscoveryAgent"

wait_for_process_to_start() {
	echo "Waiting for AMPDevicesAgent"
    while ! pgrep -x "$DevAgent" > /dev/null; do
        sleep 1
    done
    echo "Waiting for AMPDevicesAgent to die"
    while pgrep -x "$DevAgent" > /dev/null; do
        sleep 1
    done
    echo "AMPDevicesAgent died"
}

kill_process() {
    pkill -9 "$DiscoAgent"
    echo "killed AMPDeviceDiscoveryAgent!"
}
# Wait for the process to start
wait_for_process_to_start

# Kill the other process
kill_process

# Launch the program
echo "Done!"
