#!/bin/bash
# RestoreFixer 1.1 (4/23/2024) by Gordon Emmerson at Retrospekt

DevAgent="AMPDevicesAgent"

DiscoAgent="AMPDeviceDiscoveryAgent"

DiscoAgentPath="/System/Library/PrivateFrameworks/AMPDevices.framework/Versions/A/Support/AMPDeviceDiscoveryAgent"

wait_for_process_to_start() {
        echo "RestoreFixer 1.1 (4/23/2024) by Gordon Emmerson at Retrospekt"
        echo "Connect your device and select "Restore iPod" in the sync window to continue."
        echo "Do not close this window until the process is complete."
        while ! pgrep -x "$DevAgent" > /dev/null; do
                sleep 1
        done
        echo "Waiting for restore to begin."
        while pgrep -x "$DevAgent" > /dev/null; do
                sleep 1
        done
        echo "Restore complete! Beginning fix..."
        pkill -9 "$DiscoAgent"
        echo "Successfully fixed! Waiting for background programs to start..."
        sleep 5
        echo "Done! You can now close this window!"
}

wait_for_process_to_start

